housings_read:
  path: /{id}
  controller: App\Controller\HousingController::readAction
  methods: OPTIONS|GET

housings_update:
  path: /{id}
  controller: App\Controller\HousingController::updateAction
  methods: OPTIONS|PUT

housings_create:
  path: /
  controller: App\Controller\HousingController::createAction
  methods: OPTIONS|POST
