rents_read:
  path: /{id}
  controller: App\Controller\RentController::readAction
  methods: OPTIONS|GET

rents_book:
  path: /
  controller: App\Controller\RentController::bookAction
  methods: OPTIONS|POST

rents_cancel:
  path: /{id}
  controller: App\Controller\RentController::cancelAction
  methods: OPTIONS|DELETE